### ISSUE TITLE
I beat time, water and space!

### ISSUE THREAD

**Issue by dimitrilahaye** [bdeglane/dryfield-react#1]
Hi Benoît,
I played dryfield game but suddenly, I was over-full of water in my 3 fields! But all has been blocked in time, my water freezed, my field too. Perhaps I'm a crazy clicker..
See joined pic ;)

Dim (2 flics à Kiabi)
![support](https://cloud.githubusercontent.com/assets/7722597/21455693/b6aa96ac-c922-11e6-9412-0a085407341b.PNG)

**Comment by aldebaarane** [comment]
Hi Dim,

Thanks to played a unfinished already released game... The feature "finish the game without any bugs" :/ is not implement. I problably try a kickstarter campaing for that ;) 

Benoît

**Comment by dimitrilahaye** [comment]
Bad idea, I've sent some money to a KickStarter named "Help us to release a stable Windows" two years ago, and it was a big scam..
